### PR TITLE
automatic support for 3d charts

### PR DESCRIPTION
**Pull request by cornernote**

### CODE REVIEW

**Comment by cornernote** [comment]
travis timed out on one of the jobs, can you retry the build ?

**Comment by tonydspaniard** [comment]
Is this active?

**Comment by tonydspaniard** [comment]
retry executed @cornernote

**Comment by cornernote** [comment]
I submitted 2 PRs that were similar, to give you the choice of how to implement it.  I actually prefer this to the method I had in #12, but as long as there is support for 3d i dont mind how its done.

This way was more automatic than the method in #12.

**Comment by tonydspaniard** [comment]
#12 merged

**Pull request closed without merging**
